version: '3.8'

services:
  db:
    container_name: kyudo_tori_db
    image: postgres:14.17-bullseye
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DB_USER}", "-d", "${DB_NAME}"]
      interval: 5s
      retries: 5
      start_period: 10s

  app:
    build: .
    container_name: kyudo_tori_api
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=kyudo_tori_db
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
    ports:
      - "8000:8000"
    command: bash -c "
        sleep 5
        && alembic upgrade head
        && python -m app.seeds.seed
        && uvicorn app.main:app --proxy-headers --host 0.0.0.0 --port 8000
      "

volumes:
  db_data:
