"""Initial migration

Revision ID: 1d433727f57c
Revises: 
Create Date: 2025-04-05 13:37:22.800327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d433727f57c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dans_id'), 'dans', ['id'], unique=False)
    op.create_table('shinsas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('reg_start_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reg_end_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('location', 'start_at', name='u_shinsa_locationdate')
    )
    op.create_index(op.f('ix_shinsas_id'), 'shinsas', ['id'], unique=False)
    op.create_index(op.f('ix_shinsas_name'), 'shinsas', ['name'], unique=False)
    op.create_table('shinsas_dans',
    sa.Column('shinsa_id', sa.UUID(), nullable=False),
    sa.Column('dan_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['dan_id'], ['dans.id'], ),
    sa.ForeignKeyConstraint(['shinsa_id'], ['shinsas.id'], ),
    sa.PrimaryKeyConstraint('shinsa_id', 'dan_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shinsas_dans')
    op.drop_index(op.f('ix_shinsas_name'), table_name='shinsas')
    op.drop_index(op.f('ix_shinsas_id'), table_name='shinsas')
    op.drop_table('shinsas')
    op.drop_index(op.f('ix_dans_id'), table_name='dans')
    op.drop_table('dans')
    # ### end Alembic commands ###
