"""Initial migration

Revision ID: bf8dd5eded27
Revises: 
Create Date: 2025-04-03 19:43:38.767133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bf8dd5eded27'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shogos')
    op.alter_column('dans', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True)
    op.alter_column('dans', 'level',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_dans_id'), 'dans', ['id'], unique=False)
    op.alter_column('shinsas', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True)
    op.alter_column('shinsas', 'location',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True)
    op.alter_column('shinsas', 'start_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.create_index(op.f('ix_shinsas_id'), 'shinsas', ['id'], unique=False)
    op.create_index(op.f('ix_shinsas_name'), 'shinsas', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shinsas_name'), table_name='shinsas')
    op.drop_index(op.f('ix_shinsas_id'), table_name='shinsas')
    op.alter_column('shinsas', 'start_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('shinsas', 'location',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False)
    op.alter_column('shinsas', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False)
    op.drop_index(op.f('ix_dans_id'), table_name='dans')
    op.alter_column('dans', 'level',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('dans', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False)
    op.create_table('shogos',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('level', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP AT TIME ZONE 'utc'::text)"), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP AT TIME ZONE 'utc'::text)"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='shogos_pkey')
    )
    # ### end Alembic commands ###
